### PR TITLE
Update 21/07/2021 [MDB IGNORE] [IDB IGNORE]

### PR DESCRIPTION
**Pull request by Spircen**
## What Does This PR Do
Update 21/07/2021

## Why It's Good For The Game
Update 21/07/2021

## Changelog
:cl:
Update 21/07/2021

:cl:

### CODE REVIEW

**Comment by AffectedArc07** [comment]
Please put `[MDB IGNORE] [IDB IGNORE]` in your PR title, or the repo will be blacklisted from MapDiffBot

**Comment by Spircen** [comment]
Sure, there. Thanks for that.

**Comment by AffectedArc07** [comment]
> Sure, there. Thanks for that.

No worries. Please remember to do this in the future for upstream merges.

**Review by DanaDririon — APPROVED** [review]
Lo que probé funciona así que good to go

**Comment by Spircen** [comment]
Virgencita santa por favor que esto furule. 

ReimuFumoDance

**Pull request merged**
